name: flutter_image_gallery_saver_example
description: "Demonstrates how to use the flutter_image_gallery_saver plugin."
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_image_gallery_saver:
    path: ../
  path_provider: ^2.1.5

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/